repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: no-commit-to-branch
  - repo: local
    hooks:
      - id: prettier-main
        name: Config Prettier
        entry: npm run prettier
        language: system
        pass_filenames: false
#      - id: sort-rules-main
#        name: Config Sort Spectral Ruleset
#        entry: npm run sort-rules
#        language: system
#        pass_filenames: false
#      - id: document-ruleset
#        name: Document Spectral Ruleset
#        entry: npm run document-ruleset
#        language: system
#        pass_filenames: false
