extends:
  - spectral:oas
  - ./spectral/ruleset.yml

functionsDir: ./spectral/functions

functions:
  - ensurePropertiesExample
  - ensureAllArraysHaveItemTypes
  - ensureSnakeCaseWithDigits
  - validateOperationIdNaming
  - ensureCommonHttpMethods
  - ensure4xxAnd5xxUseErrorBody
rules:
  contact-properties: off
  operation-singular-tag: off
