openapi: "3.0.0"
info:
  description: "This is a sample OAS file used to validate the spectral ruleset is in a valid state. This was based of Swagger's Pet Store."
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
  contact:
    email: "devx@bettercloud.com"
    name: "DevX"
servers:
  - url: https://petstore.bettercloud.com/capability/v1
paths:
  /pets:
    description: "Operations for the Pet resource"
    get:
      summary: List all pets
      description: "List all pets"
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
          example: 25
      responses:
        "200":
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a pet
      description: "Creates a pet resource"
      operationId: createPets
      tags:
        - pets
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /pets/{petId}:
    description: "Operations for a specific pet identified by petId"
    get:
      summary: Info for a specific pet
      description: "Retrieve details for a specific pet"
      operationId: getPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
            example: "1234"
        - name: Accept-Language
          in: header
          description: "Ut consequat ipsum sit amet ullamcorper congue. Vivamus consequat molestie erat, quis pulvinar eros. Donec non tellus quis neque pretium scelerisque. "
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: en
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
              example:
                content:
                  - id: aaa7d21e-02eb-4bb4-89dd-f855078bd99e
                    name: Set User's Manager
                    description: This action sets a user's manager in Salesforce.
                    parameters:
                      - id: 87fba1fa-226a-4f51-b82b-ab08216b1d01
                        required: true
                        name: userId
                        type: ID
                      - id: 908060ce-e3c7-4308-a059-8da6cde39fa1
                        required: true
                        name: managerId
                        type: ID
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
        - breed
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        breed:
          type: string
          enum:
            - POODLE
            - BERNESE_MOUNTAIN_DOG
            - CHIHUAHUA
            - WEST_HIGHLAND_TERRIER
            - IRISH_WOLF_HOUND
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
